import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/lib/react_query/query_provider";
import { Suspense } from "react";
import LoadingPage from "./loading";
import NavLayout from "./nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Change password",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <Suspense fallback={<LoadingPage />}>
        <NavLayout />
        {children}
      </Suspense>
    </QueryProvider>
  );
}
