import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/context/auth";
import { cn } from "@/lib/utils";
import Footer from "@/components/common/Footer";
const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(openSans.className, {
          "debug-screens": process.env.NODE_ENV === "development",
        })}
      >
        <Theme>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            themes={["blue", "light", "dark"]}
            disableTransitionOnChange
          >
            <div className="min-h-screen flex flex-col">
              <AuthProvider>
                <main className="flex-1">{children}</main>
              </AuthProvider>
              <Footer />
            </div>
            <Toaster />
          </ThemeProvider>
        </Theme>
      </body>
    </html>
  );
}
