import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/context/auth";
import { cn } from "@/lib/utils";
import Footer from "@/components/common/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            themes={["blue", "light", "dark"]}
            disableTransitionOnChange
          >
            <AuthProvider>
              <div
                className={cn(inter.className, {
                  "debug-screens": process.env.NODE_ENV === "development",
                })}
              >
                {children}
              </div>
            </AuthProvider>
          </ThemeProvider>
          <Toaster />
        </Theme>
        <Footer />
      </body>
    </html>
  );
}
