import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/lib/react_query/query_provider";
import Breadcrumb from "./breadcrumb";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <QueryProvider>
    <div>
      <Breadcrumb />
      {children}
    </div>
    </QueryProvider>;
}
