import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./TeacherProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS Teacher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <StoreProvider>{children}</StoreProvider>;
}
