import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/lib/react_query/query_provider";
import TopNav from "@/components/teacher/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <div>
        <TopNav />

        {children}
      </div>
    </QueryProvider>
  );
}
