import type { Metadata } from "next";
import QueryProvider from "@/lib/react_query/query_provider";
import NavLayout from "./nav";
import "./styles.css";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <Suspense fallback={<Loading />}>
        <NavLayout />
        {children}
      </Suspense>
    </QueryProvider>
  );
}
