import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "@/lib/react_query/query_provider";
import SideNavbar from "@/components/admin/SideNavbar";
import TopNavbar from "@/components/admin/TopNavbar";
import { Query } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <div className="min-h-screen w-full flex relative flex-col sm:flex-row">
        <TopNavbar />
        <div className="min-w-[80px] relative border-r pl-5 pr-9 pb-10 pt-24 sm:block hidden">
          <SideNavbar />
        </div>
        <div className="w-full">{children}</div>
      </div>
      <Toaster />
    </QueryProvider>
  );
}
