import type { Metadata } from "next";
import { Inter } from "next/font/google";

import StoreProvider from "../../features/admin/AdminProvider";
import SideNavbar from "@/components/admin/SideNavbar";
import TopNavbar from "@/components/admin/TopNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen w-full flex relative flex-col sm:flex-row">
      <TopNavbar />
      <div className="min-w-[80px] relative border-r pl-5 pr-9 pb-10 pt-24 sm:block hidden">
        <SideNavbar />
      </div>
      <div className="w-full p-7">
        <StoreProvider>{children}</StoreProvider>
      </div>
    </div>
  );
}
