import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import LoadingPage from "./loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Suspense fallback={<LoadingPage />}>{children}</Suspense>;
}
